// Complete year data structure with all months
const schedule = {
  months: [
    {
      name: "January",
      schedule: [
        {
          date: "01",
          sehri: "5:16 AM",
          fazr: "5:22 AM",
          juhoor: "12:06 PM",
          asr: "3:46 PM",
          magrib_iftar: "5:27 PM",
          isha: "6:45 PM",
          sunrise: "6:41 PM",
        },
        {
          date: "06",
          sehri: "5:18 AM",
          fazr: "5:24 AM",
          juhoor: "12:08 PM",
          asr: "3:50 PM",
          magrib_iftar: "5:30 PM",
          isha: "6:48 PM",
          sunrise: "6:42 PM",
        },
        {
          date: "12",
          sehri: "5:20 AM",
          fazr: "5:26 AM",
          juhoor: "12:10 PM",
          asr: "3:54 PM",
          magrib_iftar: "5:34 PM",
          isha: "6:51 PM",
          sunrise: "6:43 PM",
        },
        {
          date: "18",
          sehri: "5:20 AM",
          fazr: "5:26 AM",
          juhoor: "12:13 PM",
          asr: "3:58 PM",
          magrib_iftar: "5:38 PM",
          isha: "6:55 PM",
          sunrise: "6:43 PM",
        },
        {
          date: "24",
          sehri: "5:19 AM",
          fazr: "5:25 AM",
          juhoor: "12:14 PM",
          asr: "4:03 PM",
          magrib_iftar: "5:43 PM",
          isha: "6:59 PM",
          sunrise: "6:41 PM",
        },
        {
          date: "30",
          sehri: "5:18 AM",
          fazr: "5:24 AM",
          juhoor: "12:16 PM",
          asr: "4:07 PM",
          magrib_iftar: "5:47 PM",
          isha: "7:03 PM",
          sunrise: "6:40 PM",
        },
      ],
    },
    {
      name: "February",
      schedule: [
        {
          date: "01",
          sehri: "5:18 AM",
          fazr: "5:24 AM",
          juhoor: "12:16 PM",
          asr: "4:08 PM",
          magrib_iftar: "5:48 PM",
          isha: "7:04 PM",
          sunrise: "6:39 PM",
        },
        {
          date: "06",
          sehri: "5:16 AM",
          fazr: "5:22 AM",
          juhoor: "12:16 PM",
          asr: "4:11 PM",
          magrib_iftar: "5:52 PM",
          isha: "7:07 PM",
          sunrise: "6:37 PM",
        },
        {
          date: "12",
          sehri: "5:13 AM",
          fazr: "5:19 AM",
          juhoor: "12:16 PM",
          asr: "4:15 PM",
          magrib_iftar: "5:55 PM",
          isha: "7:10 PM",
          sunrise: "6:33 PM",
        },
        {
          date: "18",
          sehri: "5:09 AM",
          fazr: "5:15 AM",
          juhoor: "12:16 PM",
          asr: "4:18 PM",
          magrib_iftar: "5:59 PM",
          isha: "7:13 PM",
          sunrise: "6:29 PM",
        },
        {
          date: "24",
          sehri: "5:05 AM",
          fazr: "5:11 AM",
          juhoor: "12:15 PM",
          asr: "4:20 PM",
          magrib_iftar: "6:02 PM",
          isha: "7:16 PM",
          sunrise: "6:25 PM",
        },
        {
          date: "30",
          sehri: "5:02 AM",
          fazr: "5:08 AM",
          juhoor: "12:15 PM",
          asr: "4:22 PM",
          magrib_iftar: "6:04 PM",
          isha: "7:17 PM",
          sunrise: "6:21 PM",
        },
      ],
    },
    {
      name: "March",
      schedule: [
        {
          date: "01",
          sehri: "4:51 AM",
          fazr: "5:07 AM",
          juhoor: "12:14 PM",
          asr: "4:22 PM",
          magrib_iftar: "6:05 PM",
          isha: "7:18 PM",
          sunrise: "6:20 PM",
        },
        {
          date: "06",
          sehri: "4:47 AM",
          fazr: "5:03 AM",
          juhoor: "12:13 PM",
          asr: "4:24 PM",
          magrib_iftar: "6:07 PM",
          isha: "7:20 PM",
          sunrise: "6:16 PM",
        },
        {
          date: "12",
          sehri: "4:41 AM",
          fazr: "4:57 AM",
          juhoor: "12:12 PM",
          asr: "4:26 PM",
          magrib_iftar: "6:10 PM",
          isha: "7:23 PM",
          sunrise: "6:10 PM",
        },
        {
          date: "18",
          sehri: "4:45 AM",
          fazr: "4:51 AM",
          juhoor: "12:10 PM",
          asr: "4:27 PM",
          magrib_iftar: "6:12 PM",
          isha: "7:25 PM",
          sunrise: "6:04 PM",
        },
        {
          date: "24",
          sehri: "4:39 AM",
          fazr: "4:45 AM",
          juhoor: "12:08 PM",
          asr: "4:28 PM",
          magrib_iftar: "6:14 PM",
          isha: "7:28 PM",
          sunrise: "5:58 PM",
        },
        {
          date: "30",
          sehri: "4:31 AM",
          fazr: "4:37 AM",
          juhoor: "12:06 PM",
          asr: "4:29 PM",
          magrib_iftar: "6:17 PM",
          isha: "7:32 PM",
          sunrise: "5:52 PM",
        },
      ],
    },
    {
      name: "April",
      schedule: [
        {
          date: "01",
          sehri: "4:29 AM",
          fazr: "4:35 AM",
          juhoor: "12:06 PM",
          asr: "4:29 PM",
          magrib_iftar: "6:18 PM",
          isha: "7:33 PM",
          sunrise: "5:50 PM",
        },
        {
          date: "06",
          sehri: "4:24 AM",
          fazr: "4:30 AM",
          juhoor: "12:05 PM",
          asr: "4:29 PM",
          magrib_iftar: "6:20 PM",
          isha: "7:35 PM",
          sunrise: "5:45 PM",
        },
        {
          date: "12",
          sehri: "4:18 AM",
          fazr: "4:24 AM",
          juhoor: "12:03 PM",
          asr: "4:30 PM",
          magrib_iftar: "6:23 PM",
          isha: "7:38 PM",
          sunrise: "5:39 PM",
        },
        {
          date: "18",
          sehri: "4:11 AM",
          fazr: "4:17 AM",
          juhoor: "12:01 PM",
          asr: "4:30 PM",
          magrib_iftar: "6:25 PM",
          isha: "7:41 PM",
          sunrise: "5:34 PM",
        },
        {
          date: "24",
          sehri: "4:05 AM",
          fazr: "4:11 AM",
          juhoor: "12:00 PM",
          asr: "4:30 PM",
          magrib_iftar: "6:28 PM",
          isha: "7:45 PM",
          sunrise: "5:29 PM",
        },
        {
          date: "30",
          sehri: "4:00 AM",
          fazr: "4:06 AM",
          juhoor: "11:59 PM",
          asr: "4:31 PM",
          magrib_iftar: "6:30 PM",
          isha: "7:49 PM",
          sunrise: "5:24 PM",
        },
      ],
    },
    {
      name: "May",
      schedule: [
        {
          date: "01",
          sehri: "3:59 AM",
          fazr: "4:05 AM",
          juhoor: "11:59 PM",
          asr: "4:31 PM",
          magrib_iftar: "6:31 PM",
          isha: "7:50 PM",
          sunrise: "5:24 PM",
        },
        {
          date: "06",
          sehri: "3:53 AM",
          fazr: "4:59 AM",
          juhoor: "11:59 PM",
          asr: "4:31 PM",
          magrib_iftar: "6:33 PM",
          isha: "7:54 PM",
          sunrise: "5:20 PM",
        },
        {
          date: "12",
          sehri: "3:49 AM",
          fazr: "3:55 AM",
          juhoor: "11:58 PM",
          asr: "4:32 PM",
          magrib_iftar: "6:36 PM",
          isha: "7:58 PM",
          sunrise: "5:17 PM",
        },
        {
          date: "18",
          sehri: "3:46 AM",
          fazr: "3:52 AM",
          juhoor: "11:58 PM",
          asr: "4:33 PM",
          magrib_iftar: "6:39 PM",
          isha: "8:01 PM",
          sunrise: "5:14 PM",
        },
        {
          date: "24",
          sehri: "3:41 AM",
          fazr: "3:48 AM",
          juhoor: "11:59 PM",
          asr: "4:34 PM",
          magrib_iftar: "6:41 PM",
          isha: "8:06 PM",
          sunrise: "5:12 PM",
        },
        {
          date: "30",
          sehri: "3:40 AM",
          fazr: "3:46 AM",
          juhoor: "11:59 PM",
          asr: "4:35 PM",
          magrib_iftar: "6:45 PM",
          isha: "8:09 PM",
          sunrise: "5:10 PM",
        },
      ],
    },
    {
      name: "June",
      schedule: [
        {
          date: "01",
          sehri: "3:39 AM",
          fazr: "3:45 AM",
          juhoor: "12:00 PM",
          asr: "4:35 PM",
          magrib_iftar: "6:46 PM",
          isha: "8:11 PM",
          sunrise: "5:10 PM",
        },
        {
          date: "06",
          sehri: "3:38 AM",
          fazr: "3:44 AM",
          juhoor: "12:01 PM",
          asr: "4:36 PM",
          magrib_iftar: "6:47 PM",
          isha: "8:13 PM",
          sunrise: "5:10 PM",
        },
        {
          date: "12",
          sehri: "3:38 AM",
          fazr: "3:44 AM",
          juhoor: "12:02 PM",
          asr: "4:38 PM",
          magrib_iftar: "6:50 PM",
          isha: "8:16 PM",
          sunrise: "5:10 PM",
        },
        {
          date: "18",
          sehri: "3:38 AM",
          fazr: "3:44 AM",
          juhoor: "12:03 PM",
          asr: "4:39 PM",
          magrib_iftar: "6:51 PM",
          isha: "8:18 PM",
          sunrise: "5:11 PM",
        },
        {
          date: "24",
          sehri: "3:39 AM",
          fazr: "3:45 AM",
          juhoor: "12:04 PM",
          asr: "4:40 PM",
          magrib_iftar: "6:53 PM",
          isha: "8:19 PM",
          sunrise: "5:11 PM",
        },
        {
          date: "30",
          sehri: "3:43 AM",
          fazr: "3:48 AM",
          juhoor: "12:06 PM",
          asr: "4:42 PM",
          magrib_iftar: "6:53 PM",
          isha: "8:20 PM",
          sunrise: "5:14 PM",
        },
      ],
    },
    {
      name: "July",
      schedule: [
        {
          date: "01",
          sehri: "3:42 AM",
          fazr: "3:48 AM",
          juhoor: "12:06 PM",
          asr: "4:42 PM",
          magrib_iftar: "6:54 PM",
          isha: "8:20 PM",
          sunrise: "5:14 PM",
        },
        {
          date: "06",
          sehri: "3:44 AM",
          fazr: "3:50 AM",
          juhoor: "12:07 PM",
          asr: "4:43 PM",
          magrib_iftar: "6:54 PM",
          isha: "8:20 PM",
          sunrise: "5:16 PM",
        },
        {
          date: "12",
          sehri: "3:48 AM",
          fazr: "3:54 AM",
          juhoor: "12:08 PM",
          asr: "4:43 PM",
          magrib_iftar: "6:53 PM",
          isha: "8:18 PM",
          sunrise: "5:18 PM",
        },
        {
          date: "18",
          sehri: "3:51 AM",
          fazr: "3:57 AM",
          juhoor: "12:08 PM",
          asr: "4:43 PM",
          magrib_iftar: "6:52 PM",
          isha: "8:15 PM",
          sunrise: "5:21 PM",
        },
        {
          date: "24",
          sehri: "3:55 AM",
          fazr: "4:01 AM",
          juhoor: "12:08 PM",
          asr: "4:43 PM",
          magrib_iftar: "6:49 PM",
          isha: "8:12 PM",
          sunrise: "5:24 PM",
        },
        {
          date: "30",
          sehri: "3:59 AM",
          fazr: "4:05 AM",
          juhoor: "12:08 PM",
          asr: "4:42 PM",
          magrib_iftar: "6:46 PM",
          isha: "8:07 PM",
          sunrise: "5:26 PM",
        },
      ],
    },
    {
      name: "August",
      schedule: [
        {
          date: "01",
          sehri: "4:00 AM",
          fazr: "4:06 AM",
          juhoor: "12:08 PM",
          asr: "4:42 PM",
          magrib_iftar: "6:45 PM",
          isha: "8:05 PM",
          sunrise: "5:27 PM",
        },
        {
          date: "06",
          sehri: "4:04 AM",
          fazr: "4:10 AM",
          juhoor: "12:08 PM",
          asr: "4:41 PM",
          magrib_iftar: "6:42 PM",
          isha: "8:01 PM",
          sunrise: "5:29 PM",
        },
        {
          date: "12",
          sehri: "4:07 AM",
          fazr: "4:13 AM",
          juhoor: "12:07 PM",
          asr: "4:39 PM",
          magrib_iftar: "6:38 PM",
          isha: "7:56 PM",
          sunrise: "5:32 PM",
        },
        {
          date: "18",
          sehri: "4:11 AM",
          fazr: "4:17 AM",
          juhoor: "12:05 PM",
          asr: "4:37 PM",
          magrib_iftar: "6:33 PM",
          isha: "7:50 PM",
          sunrise: "5:34 PM",
        },
        {
          date: "24",
          sehri: "4:14 AM",
          fazr: "4:20 AM",
          juhoor: "12:04 PM",
          asr: "4:34 PM",
          magrib_iftar: "6:28 PM",
          isha: "7:44 PM",
          sunrise: "5:36 PM",
        },
        {
          date: "30",
          sehri: "4:17 AM",
          fazr: "4:23 AM",
          juhoor: "12:02 PM",
          asr: "4:30 PM",
          magrib_iftar: "6:22 PM",
          isha: "7:37 PM",
          sunrise: "5:39 PM",
        },
      ],
    },
    {
      name: "September",
      schedule: [
        {
          date: "01",
          sehri: "4:18 AM",
          fazr: "4:24 AM",
          juhoor: "12:02 PM",
          asr: "4:29 PM",
          magrib_iftar: "6:20 PM",
          isha: "7:35 PM",
          sunrise: "5:39 PM",
        },
        {
          date: "06",
          sehri: "4:21 AM",
          fazr: "4:27 AM",
          juhoor: "12:00 PM",
          asr: "4:25 PM",
          magrib_iftar: "6:15 PM",
          isha: "7:30 PM",
          sunrise: "5:41 PM",
        },
        {
          date: "12",
          sehri: "4:23 AM",
          fazr: "4:29 AM",
          juhoor: "11:58 PM",
          asr: "4:21 PM",
          magrib_iftar: "6:09 PM",
          isha: "7:23 PM",
          sunrise: "5:43 PM",
        },
        {
          date: "18",
          sehri: "4:26 AM",
          fazr: "4:32 AM",
          juhoor: "11:56 PM",
          asr: "4:17 PM",
          magrib_iftar: "6:03 PM",
          isha: "7:16 PM",
          sunrise: "5:46 PM",
        },
        {
          date: "24",
          sehri: "4:28 AM",
          fazr: "4:34 AM",
          juhoor: "11:54 PM",
          asr: "4:12 PM",
          magrib_iftar: "5:57 PM",
          isha: "7:10 PM",
          sunrise: "5:47 PM",
        },
        {
          date: "30",
          sehri: "4:30 AM",
          fazr: "4:36 AM",
          juhoor: "11:52 PM",
          asr: "4:07 PM",
          magrib_iftar: "5:50 PM",
          isha: "7:03 PM",
          sunrise: "5:49 PM",
        },
      ],
    },
    {
      name: "October",
      schedule: [
        {
          date: "01",
          sehri: "4:31 AM",
          fazr: "4:37 AM",
          juhoor: "11:51 PM",
          asr: "4:06 PM",
          magrib_iftar: "5:49 PM",
          isha: "7:02 PM",
          sunrise: "5:49 PM",
        },
        {
          date: "06",
          sehri: "4:33 AM",
          fazr: "4:39 AM",
          juhoor: "11:50 PM",
          asr: "4:02 PM",
          magrib_iftar: "5:44 PM",
          isha: "6:57 PM",
          sunrise: "5:51 PM",
        },
        {
          date: "12",
          sehri: "4:35 AM",
          fazr: "4:41 AM",
          juhoor: "11:49 PM",
          asr: "3:57 PM",
          magrib_iftar: "5:39 PM",
          isha: "6:52 PM",
          sunrise: "5:54 PM",
        },
        {
          date: "18",
          sehri: "4:37 AM",
          fazr: "4:43 AM",
          juhoor: "11:47 PM",
          asr: "3:53 PM",
          magrib_iftar: "5:33 PM",
          isha: "6:47 PM",
          sunrise: "5:57 PM",
        },
        {
          date: "24",
          sehri: "4:40 AM",
          fazr: "4:46 AM",
          juhoor: "11:46 PM",
          asr: "3:48 PM",
          magrib_iftar: "5:28 PM",
          isha: "6:42 PM",
          sunrise: "6:00 PM",
        },
        {
          date: "30",
          sehri: "4:42 AM",
          fazr: "4:48 AM",
          juhoor: "11:45 PM",
          asr: "3:44 PM",
          magrib_iftar: "5:24 PM",
          isha: "6:39 PM",
          sunrise: "6:03 PM",
        },
      ],
    },
    {
      name: "November",
      schedule: [
        {
          date: "01",
          sehri: "4:43 AM",
          fazr: "4:49 AM",
          juhoor: "11:45 PM",
          asr: "3:43 PM",
          magrib_iftar: "5:23 PM",
          isha: "6:38 PM",
          sunrise: "6:04 PM",
        },
        {
          date: "06",
          sehri: "4:46 AM",
          fazr: "4:52 AM",
          juhoor: "11:45 PM",
          asr: "3:41 PM",
          magrib_iftar: "5:20 PM",
          isha: "6:35 PM",
          sunrise: "6:07 PM",
        },
        {
          date: "12",
          sehri: "4:49 AM",
          fazr: "4:55 AM",
          juhoor: "11:46 PM",
          asr: "3:38 PM",
          magrib_iftar: "5:17 PM",
          isha: "6:33 PM",
          sunrise: "6:11 PM",
        },
        {
          date: "18",
          sehri: "4:52 AM",
          fazr: "4:58 AM",
          juhoor: "11:47 PM",
          asr: "3:36 PM",
          magrib_iftar: "5:15 PM",
          isha: "6:32 PM",
          sunrise: "6:15 PM",
        },
        {
          date: "24",
          sehri: "4:56 AM",
          fazr: "5:00 AM",
          juhoor: "11:49 PM",
          asr: "3:35 PM",
          magrib_iftar: "5:14 PM",
          isha: "6:31 PM",
          sunrise: "6:19 PM",
        },
        {
          date: "30",
          sehri: "4:59 AM",
          fazr: "5:05 AM",
          juhoor: "11:51 PM",
          asr: "3:35 PM",
          magrib_iftar: "5:14 PM",
          isha: "6:32 PM",
          sunrise: "6:23 PM",
        },
      ],
    },
    {
      name: "December",
      schedule: [
        {
          date: "01",
          sehri: "5:00 AM",
          fazr: "5:06 AM",
          juhoor: "11:51 PM",
          asr: "3:35 PM",
          magrib_iftar: "5:14 PM",
          isha: "6:32 PM",
          sunrise: "6:24 PM",
        },
        {
          date: "06",
          sehri: "5:03 AM",
          fazr: "5:09 AM",
          juhoor: "11:53 PM",
          asr: "3:35 PM",
          magrib_iftar: "5:14 PM",
          isha: "6:33 PM",
          sunrise: "6:28 PM",
        },
        {
          date: "12",
          sehri: "5:07 AM",
          fazr: "5:13 AM",
          juhoor: "11:56 PM",
          asr: "3:37 PM",
          magrib_iftar: "5:16 PM",
          isha: "6:35 PM",
          sunrise: "6:31 PM",
        },
        {
          date: "18",
          sehri: "5:10 AM",
          fazr: "5:16 AM",
          juhoor: "11:58 PM",
          asr: "3:39 PM",
          magrib_iftar: "5:18 PM",
          isha: "6:37 PM",
          sunrise: "6:35 PM",
        },
        {
          date: "24",
          sehri: "5:13 AM",
          fazr: "5:19 AM",
          juhoor: "12:02 PM",
          asr: "3:42 PM",
          magrib_iftar: "5:21 PM",
          isha: "6:40 PM",
          sunrise: "6:38 PM",
        },
        {
          date: "30",
          sehri: "5:15 AM",
          fazr: "5:21 AM",
          juhoor: "12:04 PM",
          asr: "3:45 PM",
          magrib_iftar: "5:25 PM",
          isha: "6:44 PM",
          sunrise: "6:40 PM",
        },
      ],
    },
  ],
};

export {
  schedule,
}